import '@afforai/citation-js-plugin-cff'
import '@afforai/citation-js-plugin-github'
import '@afforai/citation-js-plugin-npm'
import '@afforai/citation-js-plugin-yaml'
import '@afforai/citation-js-plugin-zenodo'
